baseURL = 'https://terminaldawn.dev/'
languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 5

[params.giscus]
  enable = true
  repo = "klevermonicker/terminaldawn-blog"
  repoId = "R_kgDOPIMG8g"
  category = "General"
  categoryId = "DIC_kwDOPIMG8s4CslaD"
  mapping = "pathname"
  theme = "dark"

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 4
  fullWidthTheme = true
  centerTheme = true
  author = "Dan Babb"
  customCSS = ["css/custom.css"]

[params.bluesky]
  handle = "@oldsilverback.bsky.social"

[params.mastodon]
  url = "https://mastodon.social/@klevermonicker"

[languages]
  [languages.en]
    title = 'TerminalDawn'
    subtitle = "Building resilient off-grid compute"
    keywords = "off-grid, computing, raspberry pi, solar power, self-hosted"
    copyright = "TerminalDawn"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "TerminalDawn"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "hardware"
        name = "Hardware"
        url = "/hardware"
